palladiumkenya/openmrs-esm-patient-management

.github/workflows/ci.yml

assets deployment to data

---

.github/workflows/ci.yml

workflow updated to point to local servers

---

.github/workflows/ci.yml

updating Dist url

---

.github/workflows/ci.yml

folder changes

---

.github/workflows/ci.yml

updating to new folder

---

package.json
packages/esm-active-visits-app/package.json
packages/esm-appointments-app/package.json
packages/esm-patient-list-management-app/package.json
packages/esm-patient-registration-app/package.json
packages/esm-patient-search-app/package.json
packages/esm-service-queues-app/package.json
packages/esm-ward-app/package.json
packages/esm-ward-app/translations/en.json

Trying to keep the system working without community breaking changes

(release) version 7.0.2 kenyaemr

---

packages/esm-service-queues-app/src/hooks/useQueueEntries.ts
packages/esm-service-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx
packages/esm-service-queues-app/src/queue-table/default-queue-table.component.tsx

Attempt to fix null query params

(fix) remove null values from queues query params

---

packages/esm-patient-registration-app/src/offline.resources.ts

(fix) identifier sources

---

packages/esm-patient-registration-app/src/patient-verification/patient-verification-utils.ts
packages/esm-patient-registration-app/src/patient-verification/patient-verification.component.tsx

Patient identifier mapping to fields now working

---

packages/esm-service-queues-app/src/hooks/useQueueEntries.ts
packages/esm-service-queues-app/src/hooks/useQueueService.ts
packages/esm-service-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx
packages/esm-service-queues-app/src/queue-table/default-queue-table.component.tsx

Fix queues to filter services correctly by locations

---

packages/esm-patient-registration-app/src/patient-registration/field/dob/dob.component.tsx

[Screencast from 16-07-2024 05:56:02 ALASIRI.webm](https://github.com/user-attachments/assets/8f2f8b9a-e605-4447-9872-10ea588fb5f5)

Fix dob date picker increasing selected date by a month

---

packages/esm-patient-registration-app/src/config-schema.ts
packages/esm-patient-registration-app/src/patient-registration/section/patient-verification/hie-client-registry/hie-client-registry.resource.tsx

Adding additional identifier types for alient id and refugee id

---

packages/esm-patient-registration-app/src/patient-registration/field/obs/obs-field.component.tsx
packages/esm-patient-registration-app/src/patient-verification/patient-verification-hook.tsx
packages/esm-patient-registration-app/src/patient-verification/patient-verification.component.tsx
packages/esm-patient-registration-app/src/patient-verification/patient-verification.scss

Fix obs failing when still loading and enhance client registry work.

(feat) : enhance registry UI and add null check for obs concept

---

packages/esm-patient-registration-app/src/client-registry/hie-client-registry/modal/confirm-hie.modal.tsx
packages/esm-patient-registration-app/translations/en.json
packages/esm-ward-app/package-lock.json
packages/esm-ward-app/src/constant.ts

Add undefined check on martial status

(fix) add optional chaning on maritial status

---

packages/esm-patient-registration-app/src/client-registry/hie-client-registry/hie-resource.ts

(fix) use socialHealthAuthorityIdentificationNumber

---

package.json
packages/esm-active-visits-app/package.json
packages/esm-appointments-app/package.json
packages/esm-bed-management-app/package.json
packages/esm-patient-list-management-app/package.json
packages/esm-patient-registration-app/package.json
packages/esm-patient-search-app/package.json
packages/esm-service-queues-app/package.json
packages/esm-ward-app/package.json

(release) update to version 8.1.0

---

package.json
packages/esm-active-visits-app/package.json
packages/esm-appointments-app/package.json
packages/esm-bed-management-app/package.json
packages/esm-patient-list-management-app/package.json
packages/esm-patient-registration-app/package.json
packages/esm-patient-registration-app/src/patient-registration/patient-registration-hooks.ts
packages/esm-patient-search-app/package.json
packages/esm-service-queues-app/package.json
packages/esm-ward-app/package.json
yarn.lock

(chore) minor fix and framework update

---

.gitignore
packages/esm-patient-registration-app/src/client-registry/hie-client-registry/hie-resource.ts

Use Social Health Authority Identification Number

(feat) : Use social health authority identification number

---

package.json
packages/esm-active-visits-app/package-lock.json
packages/esm-active-visits-app/package.json
packages/esm-appointments-app/package.json
packages/esm-bed-management-app/package-lock.json
packages/esm-bed-management-app/package.json
packages/esm-patient-list-management-app/package-lock.json
packages/esm-patient-list-management-app/package.json
packages/esm-patient-registration-app/package-lock.json
packages/esm-patient-registration-app/package.json
packages/esm-patient-search-app/package-lock.json
packages/esm-patient-search-app/package.json
packages/esm-service-queues-app/package-lock.json
packages/esm-service-queues-app/package.json
packages/esm-ward-app/package-lock.json
packages/esm-ward-app/package.json

(release) : update to v8.0.2

---

packages/esm-patient-registration-app/src/client-registry/hie-client-registry/hie-resource.ts
packages/esm-patient-registration-app/src/client-registry/hie-client-registry/modal/confirm-hie.modal.tsx
packages/esm-patient-registration-app/src/client-registry/hie-client-registry/modal/confirm-hie.scss

…ation form
- fixed First Name and second name concatenating as first name
- Masking names (last digits)
https://github.com/user-attachments/assets/0b5ee36a-88ff-4bc8-bf3c-d33e432a82c0

Masking names and fixed First Name and second name concatenating as first name

---

packages/esm-patient-registration-app/src/client-registry/hie-client-registry/hie-client-registry.component.tsx

(refactor) renaming of the empty client registry modal

---

packages/esm-patient-search-app/src/compact-patient-search-extension/index.tsx

Fix failing search used outside patient search

(fix) : ensure search params does not fail search extension

---

yarn.lock

(chore) : bump peer dependencies

---

packages/esm-ward-app/src/ward-workspace/bed-selector.component.tsx
yarn.lock

(chore) : bump peer dependencies 

---

packages/esm-patient-search-app/package.json
packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.component.tsx
packages/esm-patient-search-app/src/config-schema.ts
packages/esm-patient-search-app/src/index.ts
packages/esm-patient-search-app/src/mpi/mpi-patien-banner.component.tsx
packages/esm-patient-search-app/src/mpi/mpi-patient-banner.scss
packages/esm-patient-search-app/src/mpi/otp-authentication.modal.tsx
packages/esm-patient-search-app/src/mpi/otp-authentication.resource.tsx
packages/esm-patient-search-app/src/mpi/otp-authentication.scss
packages/esm-patient-search-app/src/mpi/utils.ts
packages/esm-patient-search-app/src/patient-search-page/patient-banner/banner/patient-banner.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-search-views.component.tsx
packages/esm-patient-search-app/src/patient-search.resource.tsx
packages/esm-patient-search-app/src/routes.json
packages/esm-patient-search-app/src/types/index.ts
packages/esm-patient-search-app/translations/en.json
yarn.lock

(feat) : Adapt MPI workflow to work with MOH HIE

---

packages/esm-patient-registration-app/src/patient-registration/patient-registration.component.tsx
packages/esm-patient-search-app/src/mpi/mpi-patien-banner.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-banner/banner/patient-banner.component.tsx

(feat) : Retire old CR and HIE workflow

(feat) : Retire old CR and HIE workflow

---

packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.component.tsx
packages/esm-patient-search-app/src/mpi/otp-authentication.modal.tsx
packages/esm-patient-search-app/src/mpi/otp-authentication.resource.tsx
packages/esm-patient-search-app/src/mpi/utils.ts
packages/esm-patient-search-app/src/patient-search-bar/patient-search-bar.component.tsx
packages/esm-patient-search-app/src/patient-search-icon/patient-search-icon.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-search-lg.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-search-page.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-search-views.component.tsx
packages/esm-patient-search-app/src/patient-search.resource.tsx

(feat) : Add ability to perform HIE search first

---

packages/esm-patient-search-app/src/mpi/otp-authentication.modal.tsx

(fix) : uncommet code for disabling continue to chart

---

package.json
packages/esm-patient-search-app/package.json
packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.component.tsx
packages/esm-patient-search-app/src/config-schema.ts
packages/esm-patient-search-app/src/index.ts
packages/esm-patient-search-app/src/mpi/hie-syc.modal.tsx
packages/esm-patient-search-app/src/mpi/hie.sync.scss
packages/esm-patient-search-app/src/mpi/otp-authentication.resource.tsx
packages/esm-patient-search-app/src/patient-search-icon/patient-search-icon.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-search-page.component.tsx
packages/esm-patient-search-app/src/patient-search-page/patient-search-views.component.tsx
packages/esm-patient-search-app/src/patient-search.resource.tsx
packages/esm-patient-search-app/src/routes.json
yarn.lock

https://palladiumgroup-my.sharepoint.com/:i:/g/personal/donald_chelashaw_thepalladiumgroup_com/EQ31pmpYoMlNgSsZYl9ZskkBQD9lJ0Ayn0sl8uWdcDL7Gw?e=E4cffN

(feat) : Add ability to sync local with hie patient record

---

packages/esm-patient-search-app/src/mpi/otp-authentication.modal.tsx

https://thepalladiumgroup.atlassian.net/browse/KHP3-7366

Fix HIE verification bug for patients with no phone number

---

package.json
packages/esm-appointments-app/src/form/appointments-form.component.tsx

(fix) KHP3-7497 : fix all day failing validation

---

packages/esm-appointments-app/src/helpers/excel.ts

https://thepalladiumgroup.atlassian.net/browse/KHP3-7551

(fix) KHP3-7551 : Downloaded appointment excel should prefer CCC Number

---

packages/esm-appointments-app/src/appointments/details/appointment-details.component.tsx
packages/esm-appointments-app/src/appointments/details/appointment-details.test.tsx
packages/esm-appointments-app/src/appointments/unscheduled/unscheduled-appointments.component.tsx
packages/esm-appointments-app/src/helpers/excel.ts
packages/esm-appointments-app/translations/en.json

* Rename Renames Excel column gender to sex.
* Rename patient details with gender label to sex

(fix) Rename gender to sex

---

packages/esm-active-visits-app/src/active-visits-widget/active-visits.resource.tsx
packages/esm-active-visits-app/translations/en.json

* Rename header from gender to Sex

(fix) Rename gender header to sex

---

packages/esm-patient-registration-app/src/patient-registration/patient-registration-hooks.ts

See https://thepalladiumgroup.atlassian.net/browse/KHP3-7779

(fix) : KHP3-7779 : Fix Registration page doesn’t render identifiers field forcing you to refresh the page

---

packages/esm-patient-search-app/src/patient-search-page/patient-search-views.component.tsx
packages/esm-patient-search-app/src/patient-search-workspace/patient-search.workspace.tsx
packages/esm-patient-search-app/src/ui-components/overlay/overlay.scss

(fix) : ensure patient search integration with HIE work on tablet devices

---

packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.component.tsx
packages/esm-patient-search-app/src/patient-search-workspace/patient-search.workspace.tsx

(fix) : fix error with react-router context on patient search components

---

packages/esm-patient-registration-app/src/patient-registration/patient-registration-hooks.ts

(fix) : Add optional chain on obs hook

---

packages/esm-patient-search-app/src/mpi/utils.ts

fix : fix broken ci

---

packages/esm-patient-search-app/src/mpi/hie-syc.modal.tsx

(enhc) : improve patient comprasion algorithm

---

packages/esm-active-visits-app/package.json
packages/esm-appointments-app/package.json
packages/esm-bed-management-app/package.json
packages/esm-patient-list-management-app/package.json
packages/esm-patient-registration-app/package.json
packages/esm-patient-search-app/package.json
packages/esm-service-queues-app/package.json
packages/esm-ward-app/package.json
yarn.lock

chore : update openmrs dependencies
